### PR TITLE
Adding Slack form

### PR DESCRIPTION
**Pull request by DanStockham**
With the help of @jwoo92, I put together a form page on the website where new users can request invites to the slack team. This will save the admins the manual work of adding new members to slack.

The UI isn't quite polished, and all are more than welcome to clean up the form to make it more polished.

You can also review the microservice behind the form as well https://github.com/FCCColumbus/slack-ms

### CODE REVIEW

**Comment by jwoo92** [comment]
Deploy preview for *fcccolumbus* processing.

Built with commit 2a62743fa4982f1f49df3253f8da8af448f52882

https://app.netlify.com/sites/fcccolumbus/deploys/5a77af41a6188f67eeb4dcff

**Comment by jwoo92** [comment]
@DanStockham Does this include email string validation?

**Comment by DanStockham** [comment]
@jwoo92 Yes, I have the package `validator` being used in the reducer that validates the email string.

**Comment by DanStockham** [comment]
Looks like the original test on the post response was expecting `{ data: {} }`

@jwoo92 Do you still want to have this format? I have it coming in as `{ status: true }`
```
FAIL  app/helpers/api.test.js
  ✓ TDD should equal true (4ms)
  fetchCalendarData
    ✓ returns data when fetchCalendarData is called (6ms)
  postSlackInvite
    ✕ post field params to slack invite endpoint (13ms)
```

**Comment by DanStockham** [comment]
I removed the code from the api tests. The way it was testing was by posting to the production server which would work the first time, but any other test runs will fail for the slack api.

**Comment by jwoo92** [comment]
@DanStockham I typed in a non-email format value into the email input with a random name and it updated the status. Maybe it would be a good idea to validate the email field on the fly and the submit button is not enabled until so. What do you think?

**Comment by DanStockham** [comment]
@jwoo92 When you say updated the status, as in it sent it off the server? 

I had original thoughts on the submit button being active when validation is true, however, what stopped me from doing it was possible confusion for the user. On the other hand, it maybe different if the form contained more inputs.

**Pull request merged**
