### PR TITLE
 build($webpack $compile): webpack optimizations, eslint airbnb, stylelint, and prettier

### PR DESCRIPTION
**Pull request by jwoo92**
- webpack cleanup including multithreading (happypack)
- airbnb eslint config and integration
- babel stage-3 integration
- prettier formatter with eslint/stylelint integration
- stylelint integration

### CODE REVIEW

**Comment by jwoo92** [comment]
Deploy preview for *fcccolumbus* processing.

Built with commit cc768f64fa44bdab4b378b96035882e9b0b0df2b

https://app.netlify.com/sites/fcccolumbus/deploys/5a7bde340b79b73af8631fbf

**Comment by jwoo92** [comment]
The production build works fine locally, however it seems I am experiencing build issues within Netlify. I have read a few people experiencing a yarn bug related to phantomJS and Linux platforms, but can not say for certain if that is right direction yet. That is where I am at on the build error for now and I will look more into this tonight.

**Comment by DanStockham** [comment]
I attempted to do an npm install and got this error

    ```
 ⚠ The `/home/daniel/Development/F3C_Website/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
      ⚠ mozjpeg pre-build test failed
      ℹ compiling from source
      ✖ Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/home/daniel/Development/F3C_Website/node_modules/mozjpeg/vendor" --bindir="/home/daniel/Development/F3C_Website/node_modules/mozjpeg/vendor" --libdir="/home/daniel/Development/F3C_Website/node_modules/mozjpeg/vendor" && make -j2 && make install -j2
    Command failed: ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/home/daniel/Development/F3C_Website/node_modules/mozjpeg/vendor" --bindir="/home/daniel/Development/F3C_Website/node_modules/mozjpeg/vendor" --libdir="/home/daniel/Development/F3C_Website/node_modules/mozjpeg/vendor"
    configure: error: no nasm (Netwide Assembler) found
    
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```
This is from an Ubuntu 16.04 operating system

The quick fix I found was installing these dependencies, removing node_modules, and then doing a yarn or npm install

`sudo apt-get install autoconf libtool nasm`

Does this solve the Netlify issue? Not sure.

**Comment by DanStockham** [comment]
The complie time for me was a tad longer than 5 seconds. Maybe about 12 seconds.

**Comment by jwoo92** [comment]
@DanStockham I just retried the build and it worked just fine. It must of been on Netlify's end. The built time will vary depending on the computer specs its being developed on. I will need to check for merge issues now given the difference in time-frame before merging this though.

**Pull request closed without merging**
