### PR TITLE
Basic calendar

### PR DESCRIPTION
**Pull request by DanStockham**
The pull request includes a working calendar which is linked to the Eventbrite account. It displays the upcoming live events and the user can click on the event card to have another tab on the browser open with event page.

There are still some features to be added to it, though I wanted to get a working model for the site:

- Right now, error handling could be more descriptive as any error-outs will display that it didn't work
- There is no loading overlay while the site makes a request out to Eventbrite, and would aid in user experience
- The design of the event cards is basic and could be re-design for user experience.

### CODE REVIEW

**Comment by jwoo92** [comment]
Deploy preview processing.

Built with commit 5e67b87c36a015f25893e53c209eba93a5467d1e

https://app.netlify.com/sites/fcccolumbus/deploys/59e129dcdf995346a8c9daa5

**Comment by jwoo92** [comment]
I am not sure if this is a good way to go as the secret may become exposed. What are your thoughts on navigating the calendar events logic over to a micro-service on Heroku and then fetching the data from it for the calendar page @DanStockham?

**Comment by DanStockham** [comment]
I didn't think about building a micro service for just the calendar. Though
I'm down with building one.

**Comment by jwoo92** [comment]
I would be up for pairing on that idea if you wanted.

**Comment by DanStockham** [comment]
Im down. When is the best time for you?

**Comment by jwoo92** [comment]
In the deploy preview, you may notice at times that when viewing the calendar page, it seems as if it is taking a little while to fetch the data. This is due to the API being hosted on the Heroku free tier. Since it is so, sometimes it takes a few setups for the api to ramp up due to options that are in the hands of Heroku. It may not be a bad idea to explore next, and I will see if I can ramp up an API on it for a better experience.

**Pull request merged**
