### PR TITLE
Reduce size of resource icons and text

### PR DESCRIPTION
**Pull request by tyday**
Changed h2 to h3. Reduced width from 50% to 25% to allow for better flow.

### CODE REVIEW

**Comment by tyday** [comment]
I don't know how to split off the Admin fix. It just keeps adding my commits to the pull request. :D

**Comment by jwoo92** [comment]
Nice catch by the way on the admin stuff!

To make it easy, let's just reference the issue you created to keep note and can help get you situated to be a git master soon.

**Comment by jwoo92** [comment]
@tyday If you can just remove the Twitch and Youtube links, we should be good to go.

**Comment by tyday** [comment]
I can do that. 

However, I just went back and created a branch two commits ago. Would it be better if I did a pull request from there? And then followed it up with a second pull request?

https://github.com/tyday/F3C_Website/tree/Iss90

I would also need remove the links per your request.

**Comment by jwoo92** [comment]
@tyday It is no big deal and I would not worry about it on this...just something to note for another issue in the future.

**Pull request merged**
